services:
  postgres:
    container_name: livraria_bancodedados
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_USER: ${db_user}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}