services:
  postgres:
    container_name: livraria_bancodedados
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}